windowrule = float on, match:class org.telegram.desktop
windowrule = center on, match:class org.telegram.desktop
windowrule = size 1500 1200, match:class org.telegram.desktop
windowrule = no_screen_share on, match:class org.telegram.desktop
