background-opacity = 0.9
background-blur-radius = 10
theme = Symfonic
bold-is-bright = true
background = #000000
selection-background = #073642
selection-foreground = #ffffff
cursor-color = #dc322f
cursor-text = #ffffff
cursor-invert-fg-bg = true
cursor-style-blink = true
palette = 0=#000000
palette = 1=#dc322f
palette = 2=#56db3a
palette = 3=#ff8400
palette = 4=#0084d4
palette = 5=#b729d9
palette = 6=#ccccff
palette = 7=#ffffff
palette = 8=#acacac
palette = 9=#dc322f
palette = 10=#56db3a
palette = 11=#ff8400
palette = 12=#0084d4
palette = 13=#b729d9
palette = 14=#ccccff
palette = 15=#ffffff
